steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/budgetbaby', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/budgetbaby']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - budgetbaby
    - --image=gcr.io/$PROJECT_ID/budgetbaby
    - --region=us-central1
    - --platform=managed
    - --allow-unauthenticated
    - --set-secrets=SECRETS_ENV=env-file:latest,FIREBASE_CREDENTIALS=firebase-service-account:latest
    - --set-env-vars=GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENV_PATH=/secrets/.env

options:
  logging: CLOUD_LOGGING_ONLY