version: '3.9'

services:
  budgetbaby:
    build: .
    container_name: budgetbaby
    ports:
      - "8080:8080"
    env_file:
      - secrets/.env
    volumes:
      - ./secrets:/app/secrets
    restart: unless-stopped
